title: "Simplest GitHub Page"
project: "Simplest GitHub Page"
description: "Test of simplest GitHub page, leveraging Jekyll without Jekyll"
author: Christopher Allen
email: ChristopherA@LifeWithAlacrity.com
twitter_username: ChristopherA
github_username:  ChristopherA
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
# theme: jekyll-theme-primer
remote_theme: pages-themes/primer
plugins:
  - jekyll-remote-theme # https://github.com/benbalter/jekyll-remote-theme
  - jekyll-default-layout # https://github.com/benbalter/jekyll-default-layout
  - jekyll-relative-links # https://github.com/benbalter/jekyll-relative-links
  - jekyll-avatar # https://github.com/benbalter/jekyll-avatar
